site_name: PaaS Tutorial
theme:
  name: material
  font: false
  features:
    - content.code.copy
    - content.action.edit
plugins:
  - print-site:
      enumerate_headings: false
      add_to_navigation: true

repo_url: https://github.com/esgi-lyon/paas-tutorial
markdown_extensions:
  - markdown.extensions.extra
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

edit_uri: ./edit/main/docs
