---

# Metallb
metallb_ip_default_mask: "{{ (ansible_default_ipv4.address + '/' + ansible_default_ipv4.netmask) }}"
metallb_ip_default_range: "{{ (metallb_ip_default_mask | ansible.utils.ipaddr('range_usable')) }}"
metallb_ip_range: ~

# waypoint external networking
waypoint_base_domain: "k3s.test"
# Use nginx ingress controller by default
k3s_disable_services: [traefik]

# waypoint internal networking
waypoint_internal_acme_network_ip: ~
waypoint_internal_acme_host: "acme-internal.{{ waypoint_base_domain }}"

# HelmChart Custom Resource Definition for cert manager
# see https://cert-manager.io/docs/configuration/acme/
cert_manager_letsencrypt_env: prod
cert_manager_namespace: kube-system
cert_manager_acme_url: "{{ letsencrypt_envs[cert_manager_letsencrypt_env] }}"
cert_manager_staging_ca_cert_url: "{{ letsencrypt_envs_ca_certs[cert_manager_letsencrypt_env] | d(none) }}"
cert_manager_email: ""
cert_manager_private_key_secret: test_secret
cert_manager_is_internal: "{{ (cert_manager_staging_ca_cert_url | d('')) != '' }}"

# HelmChart Custom Resource Definition for dex oidc connector
dex_namespace: dex
dex_hostname: "dex.{{ waypoint_base_domain }}"
dex_client_id: waypoint
dex_client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
dex_github_client_id: ~
dex_github_client_secret: ~
dex_github_client_org: ~
dex_github_client_team: ~

# HelmChart Custom Resource Definition for waypoint variables
waypoint_namespace: default
waypoint_hostname: "waypoint.{{ waypoint_base_domain }}"
api_waypoint_hostname: api.{{ waypoint_hostname }}
waypoint_version: 0.11.0

dex_github_orgs:
  - name: '{{ dex_github_client_org }}'
    teams: 
    - '{{ dex_github_client_team }}'
