---
- name: Install ingress
  include_tasks: manifests.yml
  tags: [kubeapps]
  args: { apply: { tags: [kubeapps] } }
  loop:
    - src: nginx-ingress-chart-crd.yml
      deploy: ingress-nginx-controller
      ns: kube-system

- name: Get Ingress service infos
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: ingress-nginx-controller
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: yes
    namespace: kube-system
  register: ingress_infos

- name: Check ingress service infos available
  assert:
    that:
      - ingress_infos.resources | length > 0

- name: Set ingress ip fact
  set_fact:
    kubeapps_ingress_controller_ip: "{{ ingress_infos.resources[0].spec.clusterIP|d(none) }}"
