---
- set_fact:
    waypoint_arch_lookup:
      amd64: amd64
      x86_64: amd64
      arm64: arm64
      aarch64: arm64

- set_fact:
    waypoint_arch: "{{ waypoint_arch_lookup[ansible_architecture] }}"

- name: Unzip kubeapps binary
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/waypoint/{{ waypoint_version }}/waypoint_{{ waypoint_version }}_linux_{{ waypoint_arch }}.zip"
    dest: /usr/local/bin/
    remote_src: yes
