---

- import_tasks: checks.yml
  tags: [waypoint]

- import_tasks: setup-metallb.yml
  tags: [waypoint, metallb]
  when: 
    - metallb_ip_range | d(False)
    - '"servicelb" in k3s_disable_services'

- import_tasks: setup-ingress.yml
  tags: [waypoint, ingress-nginx]

- include_tasks: manifests.yml
  tags: [waypoint]
  when: item.condition | default(true)
  args: { apply: { tags: [waypoint] } }
  loop:
    - src: coredns-custom.yml
      condition: "{{ waypoint_internal_acme_network_ip is not none }}"
      deploy: coredns
      ns: kube-system
      tasks: restart-coredns.yml
    - src: reflector-chart-crd.yml
      deploy: reflector
      ns: "{{ cert_manager_namespace }}"
      condition: "{{ cert_manager_is_internal }}"
    - src: reflector-shared.yml
      condition: "{{ cert_manager_is_internal }}"
    - src: cert-manager-chart-crd.yml
      deploy: "cert-manager"
      ns: "{{ cert_manager_namespace }}"
    - { src: dex-chart-crd.yml , deploy: "{{ dex_namespace }}" }
    - src: waypoint-chart-crd.yml
      deploy: waypoint-runner
      kind: StatefulSet
      ns: default

- import_tasks: setup-waypoint.yml
  tags: [waypoint, finalize]
