---

- name: Map ports
  kubernetes.core.k8s:
    api_version: v1
    kind: Service
    name: waypoint-ui
    namespace: "{{ waypoint_namespace }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    apply: yes
    force: yes
    definition:
      spec:
        ports:
        - name: http
          port: 80
          targetPort: http
          nodePort: 30080
        - name: https
          port: 443
          targetPort: https
          nodePort: 30443
        - name: grpc
          port: 9701
          targetPort: grpc
          nodePort: 32701
        - name: https-2
          port: 9702
          targetPort: https
          nodePort: 32702

- set_fact:
    waypoint_arch_lookup:
      amd64: amd64
      x86_64: amd64
      arm64: arm64
      aarch64: arm64

- set_fact:
    waypoint_arch: "{{ waypoint_arch_lookup[ansible_architecture] }}"

- name: Unzip waypoint binary
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/waypoint/{{ waypoint_version }}/waypoint_{{ waypoint_version }}_linux_{{ waypoint_arch }}.zip"
    dest: /usr/local/bin/
    remote_src: yes

- name: Waypoint login
  command: waypoint login -server-addr={{ waypoint_hostname }}:443 -from-kubernetes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: false

- name: Waypoint oidc
  command: |
    waypoint auth-method set oidc \
      -client-id="{{ dex_client_id }}" \
      -display-name="GitHub" \
      -description="GitHub Oauth2 over Dex Idp open id connect adapter" \
      -client-secret="{{ dex_client_secret }}" \
      -issuer=https://{{ dex_hostname }} \
      -allowed-redirect-uri="https://{{ waypoint_hostname }}/auth/oidc-callback" \
      -claim-scope="groups" \
      -list-claim-mapping="groups=groups" \
      -access-selector="\"{{ dex_github_client_org }}:{{ dex_github_client_team }}\" in list.groups" dex
  changed_when: false

- name: Recover base runner
  shell: waypoint runner list | tail -n 1 | awk '{print $1}' | xargs
  register: waypoint_runner_id
  changed_when: false

- name: Adopt runner
  command: "waypoint runner adopt {{ waypoint_runner_id.stdout }}"
  changed_when: false
