---
- name: Converge
  hosts: node-0
  become: true
  vars:
    molecule_is_test: true
    cert_manager_acme_url: https://{{ kubeapps_internal_acme_host }}:14000/dir
    cert_manager_staging_ca_cert_url: https://localhost:15000/roots/0

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  pre_tasks:

    - name: Ensure required dependencies are installed.
      package: 
        name:
          - curl
          - wget
          - unzip
        update_cache: yes
        state: present

    - name: Ensure test dependencies are installed.
      apt: 
        name:
          - dnsutils
          - less
          - vim
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install pre-requisites for k8s module
      ansible.builtin.pip:
        name:
          - openshift
          - PyYAML
          - kubernetes

    - name: dig host.docker.internal address
      command: dig +short host.docker.internal
      register: dig_host_docker_internal
      changed_when: false
      tags: [kubeapps]

    - ansible.builtin.set_fact:
        kubeapps_internal_acme_network_ip: "{{ dig_host_docker_internal.stdout }}"
      tags: [kubeapps]

    - name: Import acme certificates
      import_tasks: "../../tasks/pre-import-cert.yml"
      tags: [kubeapps]
