---
- name: Converge
  hosts: node-0
  become: true
  vars:
    molecule_is_test: true
    cert_manager_acme_url: https://{{ kubeapps_internal_acme_host }}:14000/dir
    cert_manager_staging_ca_cert_url: https://localhost:15000/roots/0
    k3s_disable_services: [traefik, servicelb]
    metallb_ip_range: 172.29.0.20-172.29.0.50
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  pre_tasks:
    - name: Ensure required dependencies are installed.
      package: 
        name:
          - curl
          - wget
          - unzip
        update_cache: yes
        state: present

    - name: Ensure test dependencies are installed.
      apt: 
        name:
          - less
          - vim
          - golang
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install pre-requisites for k8s module
      ansible.builtin.pip:
        name:
          - PyYAML
          - kubernetes

    - name: Copy pebble config and certs
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/pebble"
        dest: "/"
        directory_mode: 0755
        remote_src: false

    - name: Install pebble
      ansible.builtin.command: go install github.com/letsencrypt/pebble/...@HEAD 
      changed_when: false

    - name: Run pebble
      command: ~/go/bin/pebble -config /pebble/pebble-config.json
      async: 2592000 # 60*60*24*30 – 1 month
      poll: 0
      changed_when: false

    - ansible.builtin.set_fact:
        kubeapps_internal_acme_network_ip: "{{ ansible_default_ipv4.address }}"
      tags: [kubeapps]

    - name: Import acme certificates
      import_tasks: "../../tasks/pre-import-cert.yml"
      tags: [kubeapps]
