---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get single node
      command: kubectl get nodes
      changed_when: false
      register: kubernetes_nodes

    - name: Print list of running nodes.
      debug: var=kubernetes_nodes.stdout

    - name: Assert master node ready
      ansible.builtin.assert:
        that: '"node-0   Ready    control-plane,master" in kubernetes_nodes.stdout'

    - name: Get kubeapps service infos
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        label_selectors:
          - component in (runner, server)
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        namespace: default
      register: kubeapps_infos

    - ansible.builtin.set_fact:
        containers_statuses: "{{ kubeapps_infos.resources | map(attribute='status') | map(attribute='containerStatuses') | flatten }}"

    - ansible.builtin.debug:
        msg: "{{ containers_statuses }}"

    - name: Assertions on service kubeapps 
      assert:
        that:
          - kubeapps_infos.resources | length > 0
          - containers_statuses | selectattr('ready', 'equalto', true) | list | count == 2
