---
# vars file for role-waypoint
waypoint_k8s_ingress_class: nginx
letsencrypt_staging: https://acme-staging-v02.api.letsencrypt.org/directory
letsencrypt_prod: https://acme-v02.api.letsencrypt.org/directory

letsencrypt_envs:
  staging: '{{ letsencrypt_staging }}'
  prod: '{{ letsencrypt_prod }}'

letsencrypt_envs_ca_certs:
  staging: https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem

# Mounted in acme internal
waypoint_internal_acme_ca_file: /etc/ssl/certs/acmeca.crt
waypoint_internal_acme_ca_in_volume_crt: /etc/ssl/certs/acmeca.crt
waypoint_internal_acme_ca_extra_volumes: []
waypoint_internal_acme_ca_extra_volumes_mounts: []

# Metallb
metallb_manifests:
  - url_manifest:
      url: https://raw.githubusercontent.com/metallb/metallb/v0.13.5/config/manifests/metallb-native.yaml
      filename: metallb-native.yaml
    deploy: controller
    ns: metallb-system
  - url_manifest:
      url: https://raw.githubusercontent.com/metallb/metallb/v0.13.5/config/manifests/metallb-frr.yaml
      filename: metallb-frr.yaml

# Ingress facts
ingress_expected_svc: "{{'ingress-nginx' 
  if 'traefik' in k3s_disable_services else 'traefik' }}"
ingress_hosts_internals: 
  - "{{ dex_hostname }}"
  - "{{ waypoint_hostname }}"

ingress_hosts_internals_joined: "{{ ingress_hosts_internals | join(' ') }}"
