---
# vars file for role-waypoint
waypoint_k8s_ingress_class: traefik
letsencrypt_staging: https://acme-staging-v02.api.letsencrypt.org/directory
letsencrypt_prod: https://acme-v02.api.letsencrypt.org/directory

letsencrypt_envs:
  staging: '{{ letsencrypt_staging }}'
  prod: '{{ letsencrypt_prod }}'

letsencrypt_envs_ca_certs:
  staging: https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem

# Mounted in acme internal
waypoint_internal_acme_ca_file: /etc/ssl/certs/acmeca.crt
waypoint_internal_acme_ca_in_volume_crt: /etc/ssl/certs/acmeca.crt
waypoint_internal_acme_ca_extra_volumes: []
waypoint_internal_acme_ca_extra_volumes_mounts: []
