name: hcp-packer
on:
  push:
    branches:
      - main
    paths:
      - 'playbook/**'
      - 'packer/**'
      - .github/workflows/release-packer.yml
jobs:
  gh-release-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.6"
      - name: Generate secrets file
        env:
          SECRETS_PKVARS: ${{ secrets.SECRETS_PKVARS }}
        run: echo "${SECRETS_PKVARS}" > secrets.pkvars.hcl

      - name: Run `packer init`
        id: init
        run: "packer init ubuntu.pkr.hcl"
        working-directory: packer
      - name: Run `packer validate`
        id: validate
        run: >- 
          packer validate \
            -var-file "$(uname -ms | tr ' ' '-')-host.hcl" \
            -var-file=secrets.pkvars.hcl ubuntu.pkr.hcl
        working-directory: packer

      - name: Build Artifact
        run: >- 
          packer build \
            -var-file "$(uname -ms | tr ' ' '-')-host.hcl" \
            -var-file=secrets.pkvars.hcl ubuntu.pkr.hcl
        working-directory: packer
