name: Release Packer image
on:
  push:
    branches:
      - main
    paths:
      - 'playbook/**'
      - 'packer/**'
      - .github/workflows/release-packer.yml
jobs:
  gh-release-packer:
    runs-on: macos-latest
    name: Run Packer
    env:
      PKR_VAR_ssh_password: ${{ secrets.PKR_VAR_SSH_PASSWORD }}
      PKR_VAR_ssh_password_hash: ${{ secrets.PKR_VAR_SSH_PASSWORD_HASH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.6"

      - name: Update Homebrew
        run: |
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/qemu.rb" > .github/brew-formulae
      
      - name: Configure Homebrew cache
        uses: actions/cache@v2
        with:
          path: |
            ~/Library/Caches/Homebrew/qemu--*
            ~/Library/Caches/Homebrew/downloads/*--qemu-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install Homebrew dependencies
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install qemu

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Run `packer init`
        id: init
        run: "packer init ubuntu.pkr.hcl"
        working-directory: packer

      - name: Run `packer build`
        run: packer build -var accelerator=hvf ubuntu.pkr.hcl
        working-directory: packer
        env:
          PACKER_LOG: 1
          PACKER_LOG_PATH: packer.log

      - name: Upload packer.log on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: packer.log
          path: packer/packer.log
          retention-days: 14

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ubuntu-jammy-${{ steps.vars.outputs.sha_short }}
          prerelease: true
          files: |
            packer/.qemu-vm/ubuntu-jammy-22.04.2.qcow2
            packer/.qemu-vm/SHA256SUMS
