name: Test Charts

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
      - .github/workflows/test-helm.yml

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add repositories workaround
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      
      - name: Dependency build
        run: helm dependency build .
        working-directory: charts/microservice

      - name: Run lint
        run: helm lint .
        working-directory: charts/microservice

      - name: Run template
        run: helm template .
        working-directory: charts/microservice
