
name: Test Infra
on:
  pull_request:
    branches:
      - main
    paths: []
      # - nixos
      # - lib
      # - '*.nix'
      # - .github/workflows/test-playbook.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install python dependencies
        run: echo 'find a way to test infra with nix'
