
name: Molecule Test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'playbook/**'
      - .github/workflows/test-playbook.yml
jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
          cache: 'pip'
          cache-dependency-path: 'playbook/requirements-test.txt'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.test.txt
        working-directory: playbook

      - uses: actions/cache@v3
        with:
          path: |
            ~/.ansible/collections/ansible_collections
            ~/.ansible/roles
          key: ${{ runner.os }}-pip-${{ hashFiles('playbook/requirements.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install ansible dependencies
        run: |
          ansible-galaxy collection install -r requirements.yaml
          ansible-galaxy role install -r requirements.yaml
        working-directory: playbook

      - name: Setup vault secret
        run: printf "$ANSIBLE_VAULT_PASSWORD" > ~/.ansible/.vault        
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Cache Homebrew Packages
        id: cache-homebrew-packages
        uses: actions/cache@v3
        env:
          cache-name: homebrew-packages
        with:
          path: $(brew --prefix)
          key: ${{ matrix.os }}-${{ env.cache-name }}-docker-dnsmasq

      - run: brew install docker && colima start

      - name: Setup dnsmasq
        run: ./scripts/setup_dnsmasq.sh
        working-directory: playbook/roles/waypoint

      # Linux : https://github.com/ansible-community/molecule/issues/3818
      # - name: Test Role with molecule (without metallb)
      #   run: molecule test -- --skip-tags=metallb --extra-vars="k3s_disable_services=[traefik]"
      #   working-directory: playbook/roles/waypoint
