name: hcp-packer
on:
  pull_request:
    paths:
      - 'playbook/**'
      - 'packer/**'
      - .github/workflows/test-packer.yml
jobs:
  gh-release-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.6"
      - name: Generate secrets file
        env:
          SECRETS_PKVARS: ${{ secrets.SECRETS_PKVARS }}
        run: echo "${SECRETS_PKVARS}" > secrets.pkvars.hcl
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Run `packer init`
        id: init
        run: "packer init ubuntu.pkr.hcl"
        working-directory: packer

      - name: Run `packer validate`
        id: validate
        run: >- 
          packer validate \
            -var-file "$(uname -ms | tr ' ' '-')-host.hcl" \
            -var-file=secrets.pkrvars.hcl ubuntu.pkr.hcl
        working-directory: packer
