name: 'Test Terraform'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**.hcl'
      - 'terraform/**.tf'
      - 'terraform/**.tfvars'
      - 'terraform/**.tmpl'
      - .github/workflows/test-terraform.yml

permissions:
  pull-requests: write

jobs:
  tf-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v2

      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Terraform Init
        id: init
        run: make init

      - name: Terraform fmt
        id: fmt
        run: make fmt ARGS='-check -diff'

      - name: Terraform Validate
        id: validate
        run: make validate
