name: 'Test Terraform'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'contabo/**'
      - .github/workflows/test-terraform.yml

permissions:
  pull-requests: write

jobs:
  tf-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -diff

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
