
name: Molecule Test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'playbook/**.yaml'
      - 'playbook/**.yml'
      - 'playbook/**.txt'
      - 'playbook/**.j2'
      - 'playbook/roles/waypoint/molecule/**'
      - .github/workflows/test-playbook.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install python dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
          sudo pip install -r requirements-test.txt
        working-directory: playbook

      - uses: actions/cache@v3
        with:
          path: |
            /root/.ansible/collections/ansible_collections
            /root/.ansible/roles
          key: ${{ runner.os }}-ansible-${{ hashFiles('playbook/requirements.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-

      - name: Install ansible dependencies
        run: |
          sudo ansible-galaxy collection install -r requirements.yaml
          sudo ansible-galaxy role install -r requirements.yaml
        working-directory: playbook

      - name: Update apt cache
        run: sudo apt update

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dnsmasq
          version: 1.0
      - name: Setup dnsmasq
        run: ./molecule/default/scripts/setup_dnsmasq.sh
        working-directory: playbook/roles/waypoint

      - name: Setup vault secret
        run: echo "$ANSIBLE_VAULT_PASSWORD" | sudo tee /root/.ansible/.vault      
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Enable molecule delegated driver for CI
        run: mv -f molecule/default/molecule.ci.yml molecule/default/molecule.yml
        working-directory: playbook/roles/waypoint

      - name: Remove kubectl
        run: sudo rm -rf /usr/local/bin/kubectl

      - name: Molecule test
        run: >-
          sudo molecule test -d delegated -- \
            --extra-vars='_hosts=127.0.0.1 k3s_disable_services=[traefik]'
        working-directory: playbook/roles/waypoint
        env:
          ANSIBLE_FORCE_COLOR: 1
